version: '3'

services:

  ganache:
    image: trufflesuite/ganache-cli:latest
    container_name: '631.echo.ganache.${ENV}'
    entrypoint:
      - node
      - /app/ganache-core.docker.cli.js
      - --account
      - ${RPC_ACCOUNT}
      - --account
      - ${RPC_ACCOUNT_2}
      - --gasLimit
      - ${RPC_BLOCK_GASLIMIT}
      - --db
      - /ganache_data
      - --defaultBalanceEther
      - --verbose
      - '10000000'
    ports:
      - '56452:8545'
    volumes:
      - testrpc:/ganache_data


  migrate:
    image: registry-gitlab.pixelplex.by/631_echo/ethereum-smartcontracts:v0.8.1
    container_name: '631.echo.contracts.${ENV}'
    command: /bin/sh -c "sleep 5; npm run migrate -- --network docker;"
    depends_on:
      - ganache
    volumes:
      - ./genesis.json:/app/genesis.json


  pytests:
    environment:
      - BASE_URL=ws://echo:6311/ws
      - ETHEREUM_URL=http://ganache:8545
      - NATHAN_PK=5JkYKpRDWeY3DN4qjZRKpEfxCqmTX17fsBJhupE9DJVVmJoGh6C
      - INIT0_PK=5J6azg8iUcQEbxEaLAFrJbcdBjgKqewLF81A63NE4T2aeHCsKiE
    build: .
    command: ["python3", "test_runner.py"]
    container_name: '631.echo.pytests.${ENV}'
    depends_on:
      - echo


  echo:
    image: registry-gitlab.pixelplex.by/631_echo/echo:v0.9.0-rc.1
    container_name: '631.echo.node.${ENV}'
    hostname: 'echo'
    command: '--data-dir=/echo/datadir/
      --genesis-json=/echo/genesis.json
      --rpc-endpoint=0.0.0.0:6311
      --start-echorand
      --account-info=[\"1.2.6\",\"5J6azg8iUcQEbxEaLAFrJbcdBjgKqewLF81A63NE4T2aeHCsKiE\"]
      --account-info=[\"1.2.7\",\"5KaTLGtpGyCbod6hM2A9RETYcNn8CMR7e7LRKLi6DPDvnF1qxEm\"]
      --account-info=[\"1.2.8\",\"5KJe2KY1yVnnBwXDtTDGfmnRGdUdR4HpLTUqpsG39h6VexYQwWH\"]
      --account-info=[\"1.2.9\",\"5K3FJdakQUJvLon2dBxLNUwcHJbZxW6XBvc1AJKDCiGHPyXZadz\"]
      --account-info=[\"1.2.10\",\"5JMgujU9Zmz85buhkPQyEMXLvK7FZ6giSLjRT25uf1tpV6uPULS\"]
      --account-info=[\"1.2.11\",\"5JFDAh3DqESZEifvvB1dGgLu4Ar9WXMgx2YSwdBngR3mY9H2YGw\"]
      --account-info=[\"1.2.12\",\"5JkYKpRDWeY3DN4qjZRKpEfxCqmTX17fsBJhupE9DJVVmJoGh6C\"]
      --sidechain-committeeman=[\"1.2.6\",\"942c314672a5cba316dc03764ea5256ed9302f7704c2dd14db1f40c962accfd9\"]
      --sidechain-committeeman=[\"1.2.7\",\"1e3868b734ac73c6676fd4f5687b0b31d98bd53621bd50e4124906a7d50b1e43\"]
      --sidechain-committeeman=[\"1.2.8\",\"05a00856ddf2527e21249c22a351a093eb40e70732e4e327c01ca07587629138\"]
      --sidechain-committeeman=[\"1.2.9\",\"770be2d7d5063fecfd6322f496865d327e11fabdacfdb6e548a6e347234e5821\"]
      --sidechain-committeeman=[\"1.2.10\",\"f3d900b6ade55834ae039f06390e92f8215e45cdf42faf8d34a005636e944b38\"]
      --sidechain-committeeman=[\"1.2.11\",\"a9f4d055d7522ac1b28e84e9c8c4c8cb42924ff72f66f7d3ce00ff99622916eb\"]
      --registrar-account=\"1.2.8\"
      --api-access=/echo/access.json
      --plugins=sidechain,registration
      --sidechain-eth-node-url=ws://ganache:8545'
    ports:
      - 56451:6311
    volumes:
      - ./genesis.json:/echo/genesis.json
    depends_on:
      - ganache


volumes:
  testrpc:
